version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.6.1-browsers
    steps:
      - checkout
      - run:
          name: Install Puppeteer
          command: |
            npm install puppeteer
      - run:
          name: Set Custom String
          # Use the environment variable from the JSON payload
          command: echo "export CUSTOM_STRING=\"$CUSTOM_STRING\"" >> $BASH_ENV
      - run:
          name: Debug Environment Variables
          command: source $BASH_ENV && env | grep CUSTOM_STRING
      - run:
          name: Run Your Script
          command: node .circleci/index.js

workflows:
  version: 2
  build_and_run:
    jobs:
      - build

