version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.6.1-browsers
      
    steps:
      - checkout
      
      - run:
          name: Install Puppeteer
          command: |
            npm install puppeteer
            
      - run:
          name: Run Node.js Script
          command: |
            MY_STRING=$(echo "$CIRCLE_JOB" | jq -r '.my_string')
            echo "My String: $MY_STRING"
            node .circleci/index.js "$MY_STRING"
          
workflows:
  version: 2
  build_and_run:
    jobs:
      - build

