version: 2.1



orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - puppeteer/install
      - run:
          name: Run tests
          command: npm .circleci/index.js



