version: 2.1

jobs:
  process-custom-string:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Set Custom String as Environment Variable
          command: |
            export CUSTOM_STRING=$(cat .circleci/custom_string.txt)
      - run:
          name: Execute index.js
          command: |
            node index.js

            
workflows:
  version: 2
  build:
    jobs:
      - build


