version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: sudo apt-get update
      - run: curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: npm install puppeteer
      - run: node .circleci/index.js

 

