version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
    name: Debug Read File
    command: |
      cat .circleci/custom_string.txt

            
      - run:
          name: Run Your Script
          command: node .circleci/index.js

            
workflows:
  version: 2
  build:
    jobs:
      - build




