version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Check File Existence
          command: |
            ls -la .
            ls -la .circleci
      - run:
          name: Debug Read File
          command: |
            cat .circleci/custom_string.txt
      - run:
          name: Set Custom String as Environment Variable
          command: |
            export CUSTOM_STRING=$(cat .circleci/custom_string.txt)
      - run:
          name: Execute index.js
          command: node .circleci/index.js
            
workflows:
  version: 2
  build:
    jobs:
      - build




