version: 2.1

orbs:
  windows: circleci/windows@2.3.1

jobs:
  build:
    docker:
      - image: circleci/node:14
        
    steps:
      - checkout
      - run: npm install puppeteer
      - run: node .circleci/index.js 
