version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install puppeteer
      - run:
          name: Run Node.js file
          command: |
            export DISPLAY=:99
            Xvfb -screen 0 1024x768x24 :99 &
            node .github/workflows/as.js





 

