version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      

      
      - run: |
          npm install puppeteer
      - run: |
          node .circleci/index.js









