version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/default
    
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

      # Install Node.js using Chocolatey
      - run: |
          choco install nodejs
          refreshenv
      
      # Verify the Node.js installation
      - run: node --version
      
      # Install Puppeteer
      - run: npm install puppeteer
      
      # Run your Node.js application
      - run: node .circleci/index.js


