
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run: |
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
      - run: |
          npm install
          node .circleci/index.js
