version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: |
          curl -o nodejs.msi https://nodejs.org/dist/v14.17.6/node-v14.17.6-x64.msi
          msiexec /i nodejs.msi /quiet

      - run: |
          npm install puppeteer
      - run: |
          node .circleci/index.js









