version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.6.1-browsers
    steps:
      - checkout
      - run:
          name: Install Puppeteer
          command: |
            npm install puppeteer
      - run:
          name: Run Your Script
          command: |
            CUSTOM_STRING=$CUSTOM_STRING node .circleci/index.js

