version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout # Checkout your code

      # Install dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install puppeteer

      # Run the Node.js script that uses Puppeteer
      - run:
          name: Run Puppeteer script
          command: node .github/.circleci/index.js.js

      
     








