version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: |
          curl -sL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
      - run: |
          npm install puppeteer
      - run: |
          node .circleci/index.js
      



 

