version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      
      - run:
          name: Read text file
          command: |
            # Read the contents of custom_string.txt into an environment variable
            export TEXT_CONTENT=$(cat .circleci/custom_string.txt)
            # You can print the content to verify
            echo "Text content: $TEXT_CONTENT"
      
      - run:
          name: Run your Node.js script
          command: node .circleci/index.js
          environment:
            TEXT_CONTENT: $TEXT_CONTENT  # Pass the TEXT_CONTENT variable to the Node.js script

workflows:
  version: 2
  build:
    jobs:
      - build




