version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:latest-browsers

    steps:
      - checkout

      - run:
          name: Install Puppeteer
          command: |
            npm install puppeteer
            # or if you prefer yarn:
            # yarn add puppeteer

      - run:
          name: Run Your Script
          command: node .circleci/index.js


