version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/default
    
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

      # Install Node.js using Chocolatey
      - run: |
          choco install nodejs
          refreshenv
      
      # Add the Node.js directory to the system PATH
      - run: |
          $env:Path = "C:\Program Files\nodejs;$env:Path"
          Write-Host "PATH=$env:Path"
      
      # Verify the Node.js installation
      - run: node --version
      
      # Install Puppeteer
      - run: npm install puppeteer
      
      # Run your Node.js application
      - run: node .circleci/index.js
