version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/windows/servercore:ltsc2019

    steps:
      - run:
          name: Install Node.js
          command: |
            curl -o nodejs.zip https://nodejs.org/dist/v14.17.6/node-v14.17.6-win-x64.zip
            Expand-Archive nodejs.zip -DestinationPath C:\nodejs
            setx PATH "%PATH%;C:\nodejs"

      - run:
          name: Install dependencies and run tests
          command: |
            npm install puppeteer
      - run: |
          node .circleci/index.js


