version: 2.1

jobs:
  process-custom-string:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Process Custom String
          command: |
            # Read the custom string from a file
            CUSTOM_STRING=$(cat custom_string.txt)
            echo "Received custom string: $CUSTOM_STRING"
            # You can perform any desired operations with the custom string here

workflows:
  version: 2
  process-custom-string:
    jobs:
      - process-custom-string:
          filters:
            branches:
              only:
                - circleci-project-setup


