version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install puppeteer
      - run: node .circleci/index.js

