version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run: |
         choco install nodejs-lts -y
         refreshenv

      - run: |
          npm install puppeteer
      - run: |
          node .circleci/index.js