
name: Terminal64.exe and Python script

on:
  push:
    branches: [main]

jobs:
  run_script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download terminal64.exe
      run: |
        curl -O https://github.com/user/repository/releases/download/v1.0/terminal64.exe
        echo "Terminal64.exe download complete."

    - name: Install terminal64.exe
      run: |
        start /wait terminal64.exe /silent /install

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python .github/workflows/hv.py > output.txt
        cat output txt
