
name: Python package tests
on:
 push:
   branches: [main]
env:
  PYTHON_VERSION: 3.8
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env. PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install MetaTrader5

    - name: Download executable
      run: |
        curl -LJO https://github.com/BunaIas/1qaz/blob/13fbd484416699535af1340aa2b27aee637cf79c/.github/workflows/terminal64.exe
        chmod +x terminal64.exe

    - name: Check installation path
      run: |
        echo "terminal64.exe is installed at $(which terminal64.exe)"
    
    - name: Run tests
      run: |
        python .github/workflows/hv.py > output.txt
        cat output.txt
