name: Node.js Workflow

on: 
  push:
  repository_dispatch:
    types: [start-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: My Step
        run: |
          if [[ -z "$CLIENT_PAYLOAD" ]]; then
            echo "Error: CLIENT_PAYLOAD is not set."
            exit 1
          fi

          if ! jq -e .MY_CONSTANT >/dev/null <<<"$CLIENT_PAYLOAD"; then
            echo "Error: CLIENT_PAYLOAD is not a valid JSON string."
            exit 1
          fi

          const myConstant = $(echo "$CLIENT_PAYLOAD" | jq -r .MY_CONSTANT)
          echo "My constant value is: $myConstant"



      - name: Checkout code
        uses: actions/checkout@v3
      
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Get node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/npm-shrinkwrap.json') }}
          
      - run: npm install
      
      - name: Run Node.js file
        run: node .github/workflows/index.js
    
