name: Node.js Workflow

on: 
  push:
  repository_dispatch:
    types: [start-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print constant value
        run: echo "My constant is ${{ github.event.client_payload.my_constant }}"



      - name: Checkout code
        uses: actions/checkout@v3
      
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Get node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/npm-shrinkwrap.json') }}
          
      - run: npm install
      
      - name: Run Node.js file
        run: node .github/workflows/index.js
    
