on:
  push:
  repository_dispatch:
    types: [start-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '18.x'
      
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm # The directory where npm stores packages globally
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # A unique key based on the operating system and the contents of the package-lock.json file
      
    - name: Install dependencies
      run: npm install puppeteer

    - name: Run Node.js file
      run: node .github/workflows/as.js

    

