name: Python package tests
on:
  push:
    branches: [ main ]
env:
  MT5_EXE: "C:\Program Files (x86)\MetaTrader 5\terminal54.exe"

env:
  PYTHON_VERSION: 3.8

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        

     - name: Launch terminal
      run: start ${{ env.MT5_EXE }}
    - name: Install dependencies
      run: |
        pip install MetaTrader5
    - name: Run tests
      run: |
        python .github/workflows/hv.py > output.txt
        cat output.txt
