
name: Terminal64.exe and Python script

on:
  push:
    branches: [main]

jobs:
  run_script:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    

    

    

    

    - name: Run script
      run: |
        .github/workflows/index.js > output.txt
        cat output txt
