name: Node.js Workflow
on:
  push:
  repository_dispatch:
    types: [start-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Add caching step to restore dependencies from cache
    - name: Cache Puppeteer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js and Install dependencies
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '18.x'
    # Remove the 'npm install' command and replace with 'npm ci'
    - name: Install dependencies
      run: npm ci puppeteer

      - name: Run Node.js file
        run: node .github/workflows/index.js

