name: Node.js Workflow

on: 
  push:
  repository_dispatch:
    types: [start-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: v18
      
      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/npm-shrinkwrap.json') }}
          
      - run: npm install
      
      - name: Run Node.js file
        run: node .github/workflows/index.js
    
