name: Node.js Workflow
on:
  push:
  repository_dispatch:
    types: [start-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '18.x'

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"
      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run Node.js file
        run: node .github/workflows/index.js

