name: Python package tests
on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.8

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Set environment variables
      uses: actions/setup-python@v2
      with:
        
        PATH_TO_TERMINAL: ${{ env..github/workflows/terminal64.exe }}

    - name: Install dependencies
      run: |
        pip install MetaTrader5
    - name: Run tests
      run: |
        python .github/workflows/hv.py > output.txt
        cat output.txt
